ARG version
FROM almalinux:${version:-8}
ARG COURSE="Docker" \
      TRAINER="Siva Kumar Reddy" \
      DURATION="10 hours" \
      AUTHOR="joindevops"
RUN echo "Trainer is: ${TRAINER}, version is: ${version}"
CMD ["sleep", "200"]